// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaQ9RULWQxApPNk8dcaoFBfD1A68ObxHw',
    appId: '1:548642035467:web:28e417865462ba23b0f40e',
    messagingSenderId: '548642035467',
    projectId: 'wanzani-f633a',
    authDomain: 'wanzani-f633a.firebaseapp.com',
    storageBucket: 'wanzani-f633a.firebasestorage.app',
    measurementId: 'G-9RCHRMN1CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMekXoWCfZgfnxl7X0WbhPCFM5bqVCceE',
    appId: '1:548642035467:android:a859ef59222ec8b4b0f40e',
    messagingSenderId: '548642035467',
    projectId: 'wanzani-f633a',
    storageBucket: 'wanzani-f633a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKDTz_8i3OtimiKAVIOkpVeG0LZfDAk-Y',
    appId: '1:548642035467:ios:2a2fb668812e5e75b0f40e',
    messagingSenderId: '548642035467',
    projectId: 'wanzani-f633a',
    storageBucket: 'wanzani-f633a.firebasestorage.app',
    iosBundleId: 'com.example.wanzani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKDTz_8i3OtimiKAVIOkpVeG0LZfDAk-Y',
    appId: '1:548642035467:ios:2a2fb668812e5e75b0f40e',
    messagingSenderId: '548642035467',
    projectId: 'wanzani-f633a',
    storageBucket: 'wanzani-f633a.firebasestorage.app',
    iosBundleId: 'com.example.wanzani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaQ9RULWQxApPNk8dcaoFBfD1A68ObxHw',
    appId: '1:548642035467:web:7c26f60dfd723446b0f40e',
    messagingSenderId: '548642035467',
    projectId: 'wanzani-f633a',
    authDomain: 'wanzani-f633a.firebaseapp.com',
    storageBucket: 'wanzani-f633a.firebasestorage.app',
    measurementId: 'G-LDTX31T45L',
  );
}
